### ISSUE TITLE
Pinch to zoom out can cause a page reload

### ISSUE THREAD

**Issue by brendanjones** [mozilla-mobile/firefox-ios#11007]
## Steps to reproduce
1. Be on any website on Firefox iOS, with scroll position at or near the top of the page.
1. Pinch to zoom out
1. Zoom out enough and the page content will be pulled far enough from the top of the page that the pull to refresh action is engaged.
1. Firefox refreshes the page.

### Expected behavior
Pinch to zoom only affects zoom and cannot start a refresh action.

### Actual behavior
As above

### Device & build information
* Device: iPhone 13
* Build version: Latest as of today's date
    1. Notes
Not reproducible on Safari

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4383)

**Comment by ericswpark** [comment]
Encountered the same problem; it's easy to reproduce on any website not optimized for mobile, or websites in desktop mode. Pinch far enough and the pull to refresh functionality triggers. It shouldn't trigger when I have two fingers on the screen.

**Comment by omishah** [comment]
It's been 4 months since this issue was reported while multiple updates has been released. Still this issue has been not fixed yet. No body cares 🤦‍♂️

**Comment by wezm** [comment]
I want to add a use case where this bug is not simply an annoyance by can also cause data loss, which I experienced this morning. On any page that triggers zoom-in, when you focus a text area (such as comment box), if you want to reposition the cursor or just review what you've written and do a zoom out gesture and trigger this bug the page reloads and you lose everything you had written in the textarea, forcing you to start again.

**Comment by brendanjones** [comment]
Thanks @wezm , good addition. I forgot to add that in my report.

**Comment by polymathruby** [comment]
Safari does something interesting here:
- if you're at 100% zoom, they zoom out to the tab view
- if you're at greater that 100% zoom, then it zooms to 100% without the reload

So it's two separate behaviours here.

**Comment by omishah** [comment]
> I want to add a use case where this bug is not simply an annoyance by can also cause data loss, which I experienced this morning. On any page that triggers zoom-in when you focus a text area (such as comment box), if you want to reposition the cursor or just review what you've written and do a zoom out gesture and trigger this bug the page reloads and you lose everything you had written in the textarea, forcing you to start again.

Exactly, that's why it's super annoying. I had the same experience. But, yeah I could have mentioned the same what you just did. 😁

**Comment by samleetucker** [comment]
Found this because I’m experiencing the exact same behavior, but in Safari (iOS 16.1.1). I didn’t make the connection that pull to refresh was the culprit, so thank you!

**Comment by omishah** [comment]
The issue has been fixed in the latest version available and doesn't reload the page when zoomed out. 

Though, devs forgot to remove the reload progress icon 😛.

**Comment by brendanjones** [comment]
Nope, I just tested it on the latest version and it’s still happening.

**Comment by lmarceau** [comment]
Not sure what is being referred there, but there was no code written for this issue since it hasn't been prioritized yet. Thank you for your understanding.

**Comment by CircuitC** [comment]
Would be nice to be able to disable the pull to refresh all-together -- as is mentioned in this Firefox forum post: https://connect.mozilla.org/t5/ideas/bring-back-ability-to-disable-pull-to-refresh/idi-p/16752

**Comment by rcbevans** [comment]
I hit this by accident all the time and have lost data on sites because of it. Incredibly annoying.

**Comment by oneslash** [comment]
I can reproduce all the time, attaching a video.

https://github.com/mozilla-mobile/firefox-ios/assets/15870134/21f1b492-d16b-4248-9185-3005d1d41170

**Comment by ecbhoang** [comment]
Is there any way to fix this by coding? Haizzz, It makes me so annoyed. The page was reloaded when I zoom in or out with 2 fingers

**Comment by jfreeman81** [comment]
Regularly having this issue too. It has caused me to lose form data multiple times on sites that aren't well suited for mobile, especially those that I have to zoom in and out to use (the zooming out causing a page refresh too many times).

**Comment by omishah** [comment]
> Regularly having this issue too. It has caused me to lose form data multiple times on sites that aren't well suited for mobile, especially those that I have to zoom in and out to use (the zooming out causing a page refresh too many times).

And still devs thinks this issue is of less importance, lol 😂

**Comment by stere0123** [comment]
This is still an issue in 114.2 on iOS 16.5. 

I have experienced data loss from this **3 times** this week on different websites, by pinch zooming out of an input field, unintentionally triggering a refresh and losing everything in the input field. 

It’s so easy to do that even when I’m extra careful to avoid it, I still sometimes trigger it. I don’t really use swipe-to-refresh anyways so adding an option to toggle it off completely would be sufficient.

Safari on iOS does not have this behavior, which isn’t surprising as it’s native - but the real surprise is **Google Chrome on iOS handles this perfectly:** in Chrome, a swipe down gives a very clear refresh prompt, yet pinch to zoom out does **not** cause a refresh! If they can do it right, Firefox should be able to as well.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested that the pinch-to-zoom and pull-to-refresh are decoupled, meaning that a pinch-to-zoom will now not cause an accidental refresh of the page anymore.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v117 (33126) with iPhone 13 Pro (15.7.1).
