### ISSUE TITLE
Text disseapars while typing into search bar (causing search to return incorrect result)

### ISSUE THREAD

**Issue by OddHouseGames** [mozilla-mobile/firefox-ios#11406]
## Steps to reproduce

1. Start Firefox ioS 
2. Start typing into the search bar

### Expected behavior

- Type search query and go

### Actual behavior

- Search query resets and entered text dissapears, causing search query to return incorrect results.
- This occurs consistently every time I open Firefox and start typing into the search bar.

### Device & build information
* Device: iPhone 6S
* Build version: 102.2 (13909)
### Notes
Attachments: 

https://user-images.githubusercontent.com/62911518/180973256-f54a3ddd-02ad-4991-a634-74c260540363.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4630)

**Comment by lmarceau** [comment]
Hello @OddHouseGames, could you check the following:
- Top sites are disabled right? Does this issue happens if you have that section enabled?
- Are you signed in with a sync account?

**Comment by OddHouseGames** [comment]
> Hello @OddHouseGames, could you check the following:
> 
>     * Top sites are disabled right? Does this issue happens if you have that section enabled?
> 
>     * Are you signed in with a sync account?

- Top sites are enabled, not sure why it wasn't showing in that recording. Also after testing more, I can do the same sequence of quitting Firefox and reopening, but it is inconsistent behaviour, sometimes it happens, sometimes it doesn't. 
- Yes, I'm signed in with a sync account.

**Comment by ericswpark** [comment]
Easy way to reproduce – get an iPad with a keyboard connected. Open a new tab with the Command+T shortcut and *immediately* start typing in the query. The search box will eat the first few bits of your query.

**Comment by dnarcese** [comment]
Check if this is the same issue as #10054

**Comment by thatswinnie** [comment]
@OddHouseGames can you still reproduce this issue? I just tried and everything seems to work as expected now. 

@SimonBasca could you please try to reproduce this as well?

**Comment by OddHouseGames** [comment]
> @OddHouseGames can you still reproduce this issue? I just tried and everything seems to work as expected now.
> 
> @SimonBasca could you please try to reproduce this as well?

Looks like this one is now resolved, thanks for following up!

**Comment by ericswpark** [comment]
@OddHouseGames weird, I can still reproduce the issue on 107.0 (21907) with my iPad and keyboard. Can you re-open the issue or should I file a new one (is your issue unrelated)?

**Comment by lmarceau** [comment]
@ericswpark the Command+T keyboard shortcut creates a new tab. If it's a new tab the text in the url bar isn't kept, hence why you see it disappear. A behavior that wouldn't be expected is seeing the url bar text disappear while continuously type in inside the same tab.

**Comment by SimonBasca** [comment]
@ericswpark I belived that the issue mentioned by you is the same as https://github.com/mozilla-mobile/firefox-ios/issues/10054#issuecomment-1313448693. Let me know if you still believe this issue needs to be re-open

**Comment by ericswpark** [comment]
@SimonBasca yup that issue sounds like what I'm experiencing. Thanks!
