### ISSUE TITLE
Crash after  disable shortcuts and sponsored shortcuts and changing device orientation

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11514]
## Steps to reproduce
1. Log in to FxA
2. Delete a top site 
3. Go to homepage
4. Disable shortcuts and sponsored shortcuts
5. Change device orientation to landscape
### Expected behavior
- App should not crash.
### Actual behavior
- Firefox crashes
### Device & build information
* Device: iPhone mini 15.4
* Build version: 104.0 (14880) and main b66207372d2c8ed00bf937e3cc3d31caf99e8ef8
### Notes
Attachments: 

[Client-2022-08-04-155437.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9259839/Client-2022-08-04-155437.ips.zip)

https://user-images.githubusercontent.com/32130829/182853286-fa7f54ca-3caf-4c08-ab12-f3ef5bf7f43f.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4705)

**Comment by SimonBasca** [comment]
Reproducible on v102.2(13909) and 103 (13910)

**Comment by nbhasin2** [comment]
Hi, @SimonBasca can you try it on simulator / fennec as well. 

The crash only happened on Firefox iOS v104 but never on Fennec.

And if you have any logs then do share as that will help a lot in fixing this.

**Comment by SimonBasca** [comment]
@nbhasin2 the issue is also reproducible on simulator. Here is a video with less steps. Let me know if you are still unable to reproduce.

## Crash log attached

[Client-2022-08-04-155437.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9267637/Client-2022-08-04-155437.ips.zip)

https://user-images.githubusercontent.com/32130829/183053479-5bfbe992-cd2e-4759-b0d2-20cdb9c58f74.mp4

**Comment by lmarceau** [comment]
We'll be making a new v104 build shortly that possibly fix this problem

**Comment by lmarceau** [comment]
Turns out, this won't be fix in v104 but in v105 unless we uplift some more commits

**Comment by lmarceau** [comment]
This should be fixed with https://github.com/mozilla-mobile/firefox-ios/pull/11585

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue is still reproducible on main 0edd33a647a5efff980a9c4aa865d5c0d936a54e following the STR

**Comment by lmarceau** [comment]
@SimonBasca Do you have the crash log from that https://github.com/mozilla-mobile/firefox-ios/commit/0edd33a647a5efff980a9c4aa865d5c0d936a54e crash? I tried the STR and can't get the crash yet either on simulator or real device. Maybe the log will help me.

**Comment by SimonBasca** [comment]
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/32130829/185154828-779a57f3-d3e3-4269-a79f-c26af06a0a1a.png">

[Client-2022-08-17-170633.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/9363334/Client-2022-08-17-170633.ips.zip)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on main 3012efa1c26a05b238f348d5f2354e02e322bd59
