### ISSUE TITLE
Tabs sent from Desktop to iOS fail to open (but works on second try)

### ISSUE THREAD

**Issue by bholley** [mozilla-mobile/firefox-ios#17395]
This has been happening to me for at least a year.

## Steps to reproduce
1. Open Firefox Nightly, right click a tab, send to device, select device.
1. Notification appears on iOS, click it
1. Firefox opens but tab does not appear
1. Repeat process. This time, the tab opens.

### Device & build information
* Device: iPhone 12 Pro
* Build version: Firefox 119.2 (35843)
* First seen version: At least a year

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7799)

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

I’m able to replicate this issue; the deeplink fails to open if Firefox is not running. If the app is running, the link is handled fine via SceneDelegate.scene(_, openURLContexts:), however if the app is being launched this hook does not appear to be called, but SceneDelegate.handle(connectionOptions:) is called and I can see when the bug occurs we do have access to the notification data within that callback, including the linked URL:

(lldb) po connectionOptions.notificationResponse!.notification.request.content
<UNNotificationContent: 0x12d205c70; title: Tab received, subtitle: (null), body: https://examplelink.com, summaryArgument: (null), summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null), realert: 0, interruptionLevel: 1, relevanceScore: 0.00, filterCriteria: (null), screenCaptureProhibited: 0But the notification link does not seem to be handled by any of the existing checks there.

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Some additional info / updates on this:

  * When the app is in the foreground and Send to Device is used, we receive the URL in scene(openURLContexts) , and it's handled correctly
  * When the app isn’t running and launches to handle the notification, that callback (above) is not triggered, but we receive the APN data within:
    * userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void)
    * and also in the connectionOptions for scene(willConnectTo:)

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Quick follow-up: does anyone know why this issue is still open? Is it just waiting for QA confirmation? A fix was merged for this on 11/21/23  https://github.com/mozilla-mobile/firefox-ios/pull/17415 ( https://github.com/mozilla-mobile/firefox-ios/pull/17415|smart-link ) ) 

cc  Andrei BodeaNorberto Andres Furlan Orla Mitchell

**Comment by bholley** [comment]
This recently started happening to me again. I think it's not yet entirely fixed.

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

We have a few different open tickets for deeplinking and sent tabs that I believe are getting incorrectly conflated, which I think is leading to some confusion. This specific issue (the one that was fixed by #17415) was caused by the app being terminated (often by iOS while in the background), and the first attempt to Send to Device wouldn't open the link after tapping the notification. But the 2nd attempt would work since the app was now running.

So it was consistently reproducible with these steps:

  1. Verify iOS Firefox is terminated/jetsammed
  2. On another device, send a link to the iOS device 
  3. On receiving iOS device, tap the notification

Expected: Firefox launches and the link is opened.
Actual: Firefox launches but the link isn't opened, you have to send it again and the 2nd attempt works

I think ideally any scenarios/bugs other than the above should probably be tracked with a separate issue in order to avoid confusion. cc Norberto Andres Furlan Andrei Bodea

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v123 (38283) with iPhone 15 Pro (17.1.2).

Please note that I was able to send tabs without issue while the app was in the foreground and also while in the background by tapping on the link. 
The FF was correctly opened and the sent tab was also correctly displayed.

Please note that I’ve sent over 30 tabs.

Please note that I did this with a fresh install and also with an update from an older version.

**Comment by bholley** [comment]
I can still reproduce this consistently on Firefox 122 by letting the phone sit for a few hours (it does not reproduce if I manually kill the app, or restart the device).

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you try to reproduce leaving the app inactive for few hours?

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Re-opening to investigate.

**Comment by mattreaganmozilla** [comment]
I've only been able to replicate this bug a few times but wanted to share initial findings:

- iOS provides two API callbacks to handle incoming URLs (e.g. from a Push Notification as a result of Sent Tabs / Send to Device, or a link being tapped in another app etc.)
- These are mentioned in [Apple's docs](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app); so far it appears the client is handling these correctly, and `openURLContexts()` is triggered reliably by URLs when the app is running / backgrounded, and `willConnectTo:options:` is sent for links on a cold launch. 
- However, each time I've replicated this bug I've confirmed that neither callback is sent by iOS
- I haven't (yet) observed any client code preceding the aforementioned delegate hooks that would appear to interfere with the normal routing of the URLs
- In the case of push notifications we receive a separate callback (`userNotificationCenter:didReceive:`); this can potentially be leveraged to provide a workaround for this bug in the case of Sent Tabs / Send to Device. However this would not help with other incoming links.

I'm still investigating potential culprits in the client, though the fact that the logs suggest the two delegate methods are never triggered might indicate a possible iOS issue (I posted on Apple's Dev Forums to solicit suggestions, [thread](https://forums.developer.apple.com/forums/thread/746178)).

**Comment by cpeterso** [comment]
I still see this bug every 1-2 days. It's a hassle and sometimes I lose sent tabs because I forgot to check whether it actually arrived and resend if needed.

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

{quote}I still see this bug every 1-2 days.{quote}

I believe the last update here was that we were attempting to get feedback from Apple (and we opened a DTS ticket IIRC), due the initial findings which appeared to indicate that the iOS client doesn’t ever receive the expected system callbacks for the URL at all. The thread posted to the Apple dev forums never received a reply unfortunately and I believe our DTS was refunded and the technicians weren’t able to help. I’ve seen anecdotal reports that similar issues have also been occurring for users on other iOS apps, but AFAIK we’ve never been able to corroborate that directly, so it’s still unclear whether this is a client bug, an iOS bug, or some mix of the two. cc Jeremy Evans Norberto Andres Furlan Not sure where this ticket fits within current priorities/scope but please LMK if we may need to reopen and re-prioritize etc. Thank you

**Comment by data-sync-user** [comment]
➤ Filippo Zazzeroni commented:

I’ve tried to repro this and couldn’t on v139 i’m able to send any tabs from Firefox desktop and open it trough the notifications and i don’t see any tab lost. cc Andres Furlan

**Comment by cpeterso** [comment]
I still see this bug every 1-2 days. I just experienced it a couple minutes ago. The problem only affects the first tab I send each day, even if I had already been using Firefox iOS that morning. I receive a "Tab received" iOS notification, but tapping the notification or opening Firefox doesn't load the sent tab.

So it seems like some sync or notification service or handler is timing out overnight?

**Comment by liquidsunshine** [comment]
This happens often to me as well... and it especially stings because there doesn't seem to be a place to see "recently sent" tabs in Firefox itself. Some sort of history function would make this a lot less frustrating...

As it stands now, it is like Firefox is just randomly deleting bookmarks... the feature is too prone to data loss to trust.

**Comment by cpeterso** [comment]
I still see this bug every 1-2 days. I'm on iOS 26.3.

> * iOS provides two API callbacks to handle incoming URLs (e.g. from a Push Notification as a result of Sent Tabs / Send to Device, or a link being tapped in another app etc.)
> * These are mentioned in [Apple's docs](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app); so far it appears the client is handling these correctly, and openURLContexts() is triggered reliably by URLs when the app is running / backgrounded, and willConnectTo:options: is sent for links on a cold launch.
> * However, each time I've replicated this bug I've confirmed that neither callback is sent by iOS

@mattreaganmozilla - If we don't receive these callbacks reliably, could Firefox ask the Firefox Sync server for new sent tabs when the app is launched or focused?
