### ISSUE TITLE
Incorrect checkmarked theme after fresh install

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#18472]
**Steps to reproduce**

1. Fresh install FF. The default device theme is dark.
2. Go to theme settings, switch toggle off and observe the theme picker below.
 
**Expected behavior**
"Dark" current theme is checkmarked.

**Actual behavior**
"Light" theme is checkmarked.

Device & build information
* Device: iPhone 15 (17.0)
* Build version: v122.1 (38217)
* First seen version: v122.1 (38217)

Notes
Attachments: 
![IMG_0042-2 Medium](https://github.com/mozilla-mobile/firefox-ios/assets/133357955/e7cf6da3-059c-4426-abd0-e1bcab27a1d6)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8336)

**Comment by adudenamedruby** [comment]
This should be fixed is v9000 (and 123, really). Can we check there. I am not able to reproduce this on `main` with the theme fixes I've put in already. :)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123(38491), with iPhone 15 (17.0).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Please note that on v122.2(38550), where the bug is not fixed, we also have a threshold setting issue: the theme doesn’t update instantly according to threshold settings.

!Skype_Video (1).mp4|width=886,height=1920!

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

For context, most theme fixes are not gonna be in 122.2, so they’re all in 123 and after. 🙂
