### ISSUE TITLE
Cookies not saved after a specific scenario

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#21523]
Steps to get the app in this stage are not clear yet, but after the app gets into this stage the bug reproduces constantly.

## Steps to reproduce
1. Access news.google.com
1. Accept cookies 
1. Close the app 
1. Relaunch the app 
1. news.google.com tab opens

### Expected behavior
Cookies are already accepted

### Actual behavior
You're asked to accept the cookies again (Please see the attached video)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9803)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Matt Reagan Razvan Litianu Alina Moldovan Let me know if we should add any other detail.

**Comment by bemlw** [comment]
I can confirm no cookies are being stored, or they are being stored for around 5 minutes. I have had to log back into every website since yesterday afternoon every time I visit.

Thanks,

**Comment by oubrecht-com** [comment]
It is reported here too:
https://github.com/mozilla-mobile/firefox-ios/issues/21497

**Comment by oubrecht-com** [comment]
Forefox 128 is last good version. 129 and newer has this bug. I tried it in beta version (TestFlight).

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

We are looking into this right now. We will keep you posted. Thanks!

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Regression that was introduced with the recent private tabs change. Fix is up which corrects the problem for normal tabs. https://github.com/mozilla-mobile/firefox-ios/pull/21539 ( https://github.com/mozilla-mobile/firefox-ios/pull/21539|smart-link )

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Alina Moldovan Andrei Bodea QA testing note: this fixes a regression where users would lose cookies / get logged out of websites on normal tabs. Note that we have an existing similar issue impacting private tabs which is a longstanding bug that is related to a WebKit issue and won’t be fixed for this ticket. For testing we should test the original issue in the ticket description as well as basic regression testing of normal/private tabs and tab restoration etc. Let me know if any questions.

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

Note: fix has been merged and backported to 130 and (eventually) it should land in 129.2 once relman merges. (cc Alina Moldovan )

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v129.2 (44469), with iPhone 15 (17.5).

**Comment by fwieringen** [comment]
Can confirm that this issue is still here on IOS 18.5 and Firefox 137.2 (53903).

1. Close firefox.
2. Reopen firefox with a link to a page where you are sure that you're logged in.
3. Site is not logged in.
4. Refresh after 5 seconds.
5. Site is logged in.

Turned off the "Close private tabs" option.

1. Firefox behaves correctly and cookies are loaded.
