### ISSUE TITLE
[Tab tray refactor] [Inactive tabs]  - Website displayed directly in the inactive tabs section [Intermittent]

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22037]
**Steps to reproduce**
1. Install FF.
2. Set inactive tabs timeout to 10s from secret settings.
3. Access webmd.com
4. Open tab tray
5. Observe

**Expected behavior**
The website is displayed in the active tabs section.

**Actual behavior**
The website is displayed directly in inactive tabs section 

**Device & build information**
* Device: iPhone 15 (17.5)
* Build version: v131 (45309)
* First seen version: ? 
Notes

Attachments: 
Uploading RPReplay_Final1726584818.mp4…

**Comment by ih-codes** [comment]
It looks like your attachment failed to upload @DianaABarladeanu , so I wasn't able to check for certain, but I believe this is fixed on main now. But if it isn't, could you please upload another video?

**Comment by DianaABarladeanu** [comment]
Sorry for that @ih-codes, the bug is still reproducible. Here is a video: 

https://github.com/user-attachments/assets/d594eb9a-b28d-4ddd-adc5-1c8b7777e3a5
Verified on v9000 (45624), with iPhone 15 (17.5).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

The issue is still reproducible on v9000 (45732), with iPhone 15 (17.5).

**Comment by data-sync-user** [comment]
➤ Sophie Amin commented:

This looks like it will be fixed as part of diffable datasource work (note to self)

**Comment by data-sync-user** [comment]
➤ ih-codes commented:

FYI Sophie Amin , I still have concerns about when the lastExecutedTime is updated on the tabs (mentioned further up this thread https://github.com/mozilla-mobile/firefox-ios/issues/22037#issuecomment-2374769350 ( https://github.com/mozilla-mobile/firefox-ios/issues/22037#issuecomment-2374769350|smart-link ) ). I would expect that browsing should update this time, but it only seems to happen on tab selection.

**Comment by data-sync-user** [comment]
➤ Isabella commented:

Not resolved AFAIK.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

I’ll close this task since inactive tabs aren’t part of the app anymore
