### ISSUE TITLE
#22247 ⁃ “Go to copied link?” toast is missing “Paste” button when using larger text sizes

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#22247]
## Steps to reproduce

1. Open a page in Firefox. 
2. Switch to another app. 
3. Copy a URL from the other app. 
4. Switch back to Firefox 

### Expected behavior

Firefox should show the “Go to copied link?” with an “Go” button. 

### Actual behavior

Firefox shows the “Go to copied link?” with a button, but the button has no text label. 

### Device & build information

- Device: iPhone 15 Plus running iOS 18.0
- Build version: Firefox 9000 (45786)
- First seen version: 

### Notes

I suspect this bug is a regression caused by updating to iOS 18.0 (from iOS 17.7): I know the copied link banner’s button text used to be visible, but it’s not shown in Firefox 130.1 or any of the Nightly versions available in TestFlight going back at least 88 days.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10152)

**Comment by imkaran315** [comment]
Hi, Can I work on this issue?
I think I can solve this quickly.

**Comment by cpeterso** [comment]
@imkaran315 - That would be great! Have you built Firefox for iOS on your machine? https://github.com/mozilla-mobile/firefox-ios/wiki

If you have questions about building, you can ask in the Firefox-iOS room on Mozilla's Matrix chat server: https://chat.mozilla.org/?#/room/#fx-ios:mozilla.org

**Comment by imkaran315** [comment]
> @imkaran315 - That would be great! Have you built Firefox for iOS on your machine? https://github.com/mozilla-mobile/firefox-ios/wiki
> 
> If you have questions about building, you can ask in the Firefox-iOS room on Mozilla's Matrix chat server: https://chat.mozilla.org/?#/room/#fx-ios:mozilla.org

Yeah, mostly, it's done. But I'm stuck at a Sentry error. It is about some method not being found. I'm using the latest version of Sentry. Any help?

**Comment by RRUIZ5** [comment]
Hello!
it seems this issue is fixed and should be closed?
I cannot reproduce on iOS 18, attaching image
(sorry, forgot to change the language to english)
![imagen](https://github.com/user-attachments/assets/aae4c415-9361-4dbb-8df6-fc941b4946c1)

**Comment by cpeterso** [comment]
I can still reproduce this bug in Firefox 131.1 and Nightly 9000 (46530) on my iPhone 15 Plus running iOS 18.0.1. I tested both locale en-US and de-DE, in case this was a language issue, but it's not.

**Comment by nbhasin2** [comment]
I am on TestFlight version 135 (49854) and don't see this issue, @cpeterso what version are you on where you are encountering this bug?

<table>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/acbebfc0-db80-499d-a06b-83427de15a45" alt="Image 1" height="400"></td>
    <td><img src="https://github.com/user-attachments/assets/1abebc26-036f-4c62-b6c8-106a15b28303" alt="Image 2" height="400"></td>
  </tr>
</table>

**Comment by cpeterso** [comment]
@nbhasin2 I can reproduce with Firefox 9000 (49850) and 134.0 (49061) on my iPhone 15 Plus running iOS 18.2.1.

**Comment by nbhasin2** [comment]
This is something we need to figure out why only a few including yourself (@cpeterso) can reproduce it and not me. I am on iOS 18.3 so this isn't an iOS 18 issue but could be related to English / US vs English / Canada translation. Maybe @abodea or someone else from QA could look into this

**Comment by cpeterso** [comment]
I tested Firefox 134.0 (49061) on an iPhone 14 Pro running 18.1.1 and I was _not_ able to reproduce there. I don't know what is different about my two phones. They're both en-US. The different iOS versions, 18.1.1 and 18.2.1, shouldn't matter because I originally reported this bug on iOS 18.0.

This isn't a problem with all toast messages. The "New Tab Opened [Switch]" and "Tab Closed [Undo]" render their button text correctly. Only the "Go to copied link? [    ]" button (`ClipboardToast.GoToCopiedLink.Button`) is broken.

**Comment by cpeterso** [comment]
Aha! I found the difference.

This problem is caused by using a non-default text size on my iPhone 15 Plus. If I increase system Settings > Accessibility > Display & Text Size > Larger Text setting by two or more steps above the default size, then the "Go to copied link? [Paste]" toast omits the "Paste" label from the button.

![Image](https://github.com/user-attachments/assets/b712a7fe-eb6f-4438-afc4-87aa93c321fb)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

I was able to reproduce this issue on v135 (49962), with iPhone 15 (17.6) and iPhone 16+ (18.2), by setting the text sizing to the maximum or slightly smaller.

Also, we’ve recently logged a similar bug ( https://mozilla-hub.atlassian.net/browse/FXIOS-11073 ) for iPad.

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Karan Verma commented:*

Hi, Can I work on this issue?  
I think I can solve this quickly.

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Chris Peterson commented:*

imkaran315

- That would be great! Have you built Firefox for iOS on your machine? [https://github.com/mozilla-mobile/firefox-ios/wiki](https://github.com/mozilla-mobile/firefox-ios/wiki)

If you have questions about building, you can ask in the Firefox-iOS room on Mozilla's Matrix chat server: https://chat.mozilla.org/?#/room/#fx-ios:mozilla.org

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Karan Verma commented:*

> imkaran315

- That would be great! Have you built Firefox for iOS on your machine? [https://github.com/mozilla-mobile/firefox-ios/wiki](https://github.com/mozilla-mobile/firefox-ios/wiki)  
>   
> If you have questions about building, you can ask in the Firefox-iOS room on Mozilla's Matrix chat server: https://chat.mozilla.org/?#/room/#fx-ios:mozilla.org

Yeah, mostly, it's done. But I'm stuck at a Sentry error. It is about some method not being found. I'm using the latest version of Sentry. Any help?

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Chris Peterson commented:*

> I'm stuck at a Sentry error. It is about some method not being found. I'm using the latest version of Sentry. Any help?

I heard today that Firefox can’t be built on macOS Sequoia due to a Sentry library issue. I assume that’s the same error you’re running into.

I don’t know if there is a bug report or a workaround. I recommend asking the Firefox iOS engineers in the Firefox-iOS channel on Matrix.

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Rodrigo Ruiz Murguia commented:*

Hello!  
it seems this issue is fixed and should be closed?  
I cannot reproduce on iOS 18, attaching image  
(sorry, forgot to change the language to english)  
imagen ( [https://github.com/user-attachments/assets/aae4c415-9361-4dbb-8df6-fc941b4946c1](https://github.com/user-attachments/assets/aae4c415-9361-4dbb-8df6-fc941b4946c1) )

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Chris Peterson commented:*

I can still reproduce this bug in Firefox 131.1 and Nightly 9000 (46530) on my iPhone 15 Plus running iOS 18.0.1. I tested both locale en-US and de-DE, in case this was a language issue, but it's not.

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Nishant Bhasin commented:*

I am on TestFlight version 135 (49854) and don't see this issue, cpeterso what version are you on where you are encountering this bug?

<table>  
<tr>  
<td>[https://github.com/user-attachments/assets/acbebfc0-db80-499d-a06b-83427de15a45</td](https://github.com/user-attachments/assets/acbebfc0-db80-499d-a06b-83427de15a45%3C/td)>  
<td>[https://github.com/user-attachments/assets/1abebc26-036f-4c62-b6c8-106a15b28303</td](https://github.com/user-attachments/assets/1abebc26-036f-4c62-b6c8-106a15b28303%3C/td)>  
</tr>  
</table>

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Chris Peterson commented:*

nbhasin2 I can reproduce with Firefox 9000 (49850) and 134.0 (49061) on my iPhone 15 Plus running iOS 18.2.1.

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Nishant Bhasin commented:*

This is something we need to figure out why only a few including yourself (@cpeterso) can reproduce it and not me. I am on iOS 18.3 so this isn't an iOS 18 issue but could be related to English / US vs English / Canada translation. Maybe abodea or someone else from QA could look into this

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Chris Peterson commented:*

I tested Firefox 134.0 (49061) on an iPhone 14 Pro running 18.1.1 and I was not able to reproduce there. I don't know what is different about my two phones. They're both en-US. The different iOS versions, 18.1.1 and 18.2.1, shouldn't matter because I originally reported this bug on iOS 18.0.

This isn't a problem with all toast messages. The "New Tab Opened [Switch]" and "Tab Closed [Undo]" render their button text correctly. Only the "Go to copied link? [    ]" button (ClipboardToast.GoToCopiedLink.Button) is broken.

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ *Chris Peterson commented:*

Aha! I found the difference.

This problem is caused by using a non-default text size on my iPhone 15 Plus. If I increase system Settings > Accessibility > Display & Text Size > Larger Text setting by two or more steps above the default size, then the "Go to copied link? [Paste]" toast omits the "Paste" label from the button.

Image ( [https://github.com/user-attachments/assets/b712a7fe-eb6f-4438-afc4-87aa93c321fb](https://github.com/user-attachments/assets/b712a7fe-eb6f-4438-afc4-87aa93c321fb) )

**Comment by data-sync-user** [comment]
> **Diana Andreea Barladeanu** commented from Jira:

I was able to reproduce this issue on v135 (49962), with iPhone 15 (17.6) and iPhone 16+ (18.2), by setting the text sizing to the maximum or slightly smaller.

Also, we’ve recently logged a similar [bug](https://mozilla-hub.atlassian.net/browse/FXIOS-11073) for iPad.

**Comment by bmihai23** [comment]
Hi @FilippoZazzeroni, @PARAIPAN9, @yoanarios,
I was testing this issue on current `main` and noticed that the clipboard toast wasn’t appearing at all
It looks like `appWillEnterForegroundNotification` is currently only referenced: `self.appWillEnterForegroundNotification`
Changing it to actually call the method: `self.appWillEnterForegroundNotification()` — makes the toast appear again
After that, I tested on an iPhone 17 Pro Simulator running iOS 26.5, and the Paste label remains visible even with large Accessibility text sizes
Is this issue still something that needs work, or should the missing () be handled separately? 

| Normal Text Size | Large Accessibility Text |
| ----------------- | ------------------------ |
| <img width="479" height="906" alt="Image" src="https://github.com/user-attachments/assets/f6847a07-6f48-4972-b2c8-9293511a0a56" /> | <img width="479" height="906" alt="Image" src="https://github.com/user-attachments/assets/95a32515-7929-4e27-b69d-1f10257dc14a" /> |

**Comment by PARAIPAN9** [comment]
Thanks @bmihai23 for the invetigation. I think I'll hand it over QA team since it's very old.

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ bmihai23 commented:

Hi @FilippoZazzeroni, @PARAIPAN9, @yoanarios,
I was testing this issue on current `main` and noticed that the clipboard toast wasn’t appearing at all
It looks like `appWillEnterForegroundNotification` is currently only referenced: `self.appWillEnterForegroundNotification`
Changing it to actually call the method: `self.appWillEnterForegroundNotification()` — makes the toast appear again
After that, I tested on an iPhone 17 Pro Simulator running iOS 26.5, and the Paste label remains visible even with large Accessibility text sizes
Is this issue still something that needs work, or should the missing () be handled separately? 

| Normal Text Size | Large Accessibility Text |
| ----------------- | ------------------------ |
| <img width="479" height="906" alt="Image" src="https://github.com/user-attachments/assets/f6847a07-6f48-4972-b2c8-9293511a0a56" /> | <img width="479" height="906" alt="Image" src="https://github.com/user-attachments/assets/95a32515-7929-4e27-b69d-1f10257dc14a" /> |

**Comment by data-sync-user** [comment]
> **Data Sync** commented from Jira:

➤ PARAIPAN9 commented:

Thanks @bmihai23 for the invetigation. I think I'll hand it over QA team since it's very old.

**Comment by data-sync-user** [comment]
> **Ada Cristea** commented from Jira:

Verified on Firefox 156.1 (77034) using iPhone 11 (18.7), the issue is still reproducible; the toast is not displayed.

**Comment by data-sync-user** [comment]
> **Sorin Paraipan** commented from Jira:

This issue is in progress. A contributor is working on it. It seems that the bot updated the Fix version to 156.1 even though was not ready.

**Comment by data-sync-user** [comment]
> **Sorin Paraipan** commented from Jira:

I was the bot, haha. `@Ada Cristea` , thanks for veryfing it. I wanted to make sure that is still reproducible because it was old.

**Comment by FilippoZazzeroni** [comment]
Hi @bmihai23 thanks for trying to reproduce it, i see QA was able to reproduce the issue, but there is already an open [PR](https://github.com/mozilla-mobile/firefox-ios/pull/35280) that should fix this. cc @yoanarios
