### ISSUE TITLE
Incorrect connection type is displayed in the ETP panel

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#22581]
## Steps to reproduce

1. Open a secure page (bbc.com, google.com).
2. Tap on the "ETP lock" icon from the URL toolbar.
3. Check the connection type 

### Expected behavior
The connection type should match the connection type displayed in the addessbar

### Actual behavior
Always "Connection is not secure" is displayed together with the insecure connection icon 

### Device & build information
* Device: iPhone 14 Pro Max (iOS 16.2), iPhone 14+ (16.0.3), iPad Pro 4th Gen (18.0)  
* Build version: v9000 (46466) 
* First seen version: ? 
### Notes
Attachments: 

![image](https://github.com/user-attachments/assets/f93475b9-fdb2-46d5-989e-1087050a2488)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10308)

**Comment by PARAIPAN9** [comment]
I see that `getpocket.com` is using an `https` connection which makes the site secure, meaning that the toolbar lock icon behaves ok. It is more like a TP problem.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

What means a TP Problem?

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Norberto Andres Furlan this has to be fixed in the Tracking Protection view and not in toolbar.

**Comment by mattreaganmozilla** [comment]
Note: there was a recent fix that changed the ETP panel's `isConnectionSecure` to match whatever the lock icon is showing, which was intended to fix this exact problem. Do we know if this was tested with the most recent build? (I'm not actually sure, at this point, how it's possible for the ETP panel to show a different SSL status than the lock icon)

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, please note that the issue is still reproducible in v133 (46984) with iPhone 15 Pro (18.2).

!image-20241031-135328.png|width=33.333333333333336%,alt="image-20241031-135328.png"!

**Comment by data-sync-user** [comment]
➤ Stefan Vladut commented:

it seems this bug has been resolved on the latest main, but continues to affect version 133. Since we've backported the  PRs involved to 133, I'm curious about what's causing this discrepancy. Maybe there’s an issue with backports? Nishant Bhasin

**Comment by cpeterso** [comment]
I can still reproduce this bug in the latest Nightly build 47039 on my iPhone 15 Plus running iOS 18.1. I bisected this bug and it was a regression in Nightly build 46422.

![image](https://github.com/user-attachments/assets/55716176-84c6-49ca-a260-604cb5e9ede6)

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000(48272) with iPhone 14 Pro Max (iOS 16.2).

!ETP1.jpeg|width=430,height=932,alt="ETP1.jpeg"!

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on FF 317.0(52649) with iPhone 14 Pro Max (iOS 16.2).

[^RPReplay_Final1743166821.MP4]
