### ISSUE TITLE
Context menu bugs: dark mode support for label, favicon looks wrong, delete

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#5573]
Steps to reproduce:

1.  Opened Settings in Firefox (iOS) via Menu (Bottom Right)
2.  Opened General > Display
3.  Selected Dark
4.  Closed Settings
5.  Hold Down on a link in Top Sites

Actual results:

After going through settings to change the theme of the application from light to dark, I exited settings. After that, I held down on one of the links in the Top Sites section and the label and link of the selected link was unable to be read while in Dark Theme.

Expected results:

The expected results for this issue is that the application should've accommodated for the shift in colour with the theme change and changed the font colour so that the text is readable for the users. For example: changing the text colour from black to white when the theme changes from light to dark.

![IMG_2561](https://user-images.githubusercontent.com/1866605/66464731-2f358800-ea88-11e9-80f5-e8b4641270f6.jpg)

Cloned from Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1587250

**Comment by athomasmoz** [comment]
@SimonBasca I think this is fixed in the latest beta, do you mind retesting there? It worked for me

**Comment by SimonBasca** [comment]
I am still reproducing this issue on Firefox 20.0(16346). You can see in the video that the Youtube is barely visible. 


[RPReplay_Final1570781536.MP4.zip](https://github.com/mozilla-mobile/firefox-ios/files/3716356/RPReplay_Final1570781536.MP4.zip)

**Comment by garvankeeley** [comment]
Also the favicon looks like  it is too small within its contents, 
and,
delete button icon looks  wrong (big and fuzzy)

**Comment by garvankeeley** [comment]
This PR fixes the label colors: https://github.com/mozilla-mobile/firefox-ios/pull/5605
