### ISSUE TITLE
iOS Status bar is not visible

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5684]
Logged via Bugzilla : https://bugzilla.mozilla.org/show_bug.cgi?id=1592176

iOS 13.1.3 on iPhone Xr

**Settings Menu:**

Pre-conditions:
- Light theme selected.

Steps to reproduce:
1. Open Settings menu 

Actual results:
- iOS status bar is not displayed.
![IMG_C4C1155072EE-1](https://user-images.githubusercontent.com/32130829/67763188-c7071000-fa4f-11e9-8eba-197cd234508b.jpeg)

**System Dark Mode:**

Pre-conditions:
- FF light theme selected
- System dark theme selected

Steps to reproduce:
1. Open any webpage in FF

Actual results:
- iOS status bar is not displayed.

**Comment by SimonBasca** [comment]
This is also reproducible on webpages when iOS Theme is set to "Dark" and Firefox theme is set to "Light"

**Comment by athomasmoz** [comment]
This should be fixed. @SimonBasca do you mind testing on master?

**Comment by SimonBasca** [comment]
Still reproducible on following the STR on master 29017f6438

**Comment by athomasmoz** [comment]
Marking as a P2 because, although this is very visible now, it will happen less often once we match FF theme to system theme

**Comment by SimonBasca** [comment]
This issue is no longer reproducible after following the STR on build 20.2(16690)
