### ISSUE TITLE
Launch screen should be adapted to dark mode

### ISSUE THREAD

**Issue by nick130586** [mozilla-mobile/firefox-ios#5745]
Firefox should have a dark mode version of launch screen, like in Pocket

![IMG_0151](https://user-images.githubusercontent.com/168651/68585681-9d0c0f80-048b-11ea-87f2-560ce299487d.PNG)

**Comment by dnarcese** [comment]
This has been fixed in https://github.com/mozilla-mobile/firefox-ios/pull/5608, the changes will be out in the next release!

**Comment by SimonBasca** [comment]
This issue has been fix on master 9741a9ec, but it's still reproducible on 20.2(16690). I believe this is part of a bigger patch and will be working when https://github.com/mozilla-mobile/firefox-ios/issues/5567 lands.
