### ISSUE TITLE
Can't access websites with self-signed certificates

### ISSUE THREAD

**Issue by Scripter17** [mozilla-mobile/firefox-ios#7631]
## Steps to reproduce
Create an HTTPS server with a self-signed TLS certificate and attempt to access it via FireFox for iOS.

### Expected behavior
Give a warning that the site isn't secure, but otherwise allow the user to connect.

### Actual behavior
The progress bar at the top of the screen permanently hangs and the browser won't connect.

### Device & build information
* Device: iPhone SE
* Build version: Firefox Daylight 29.1 (3022)
### Notes
- Attempting to access the HTTPS site on Safari works as expected, and this has only been happening recently. (don't remember exactly when, sorry)
- I've tried creating a certificate authority, trusting it on my phone, then generating a certificate signed by that authority, but I keep getting stuck at the "enable full trust for root certificates" step. Might work, might not.
- Changing the HTTPS server to an HTTP one connects fine.
- The console.log at the top of my server's code won't trigger when FF connects to it as HTTPS.
- The technical details for the certificate on FireFox for Windows says `TLS_AES_256_GCM_SHA384, 256 bit keys, TLS 1.3`
- It worked *once* just now as I was testing it. It was in normal non-private mode if that helps at all.
  - Come to think of it I remember it sometimes wouldn't in private mode work unless I hit the "trust this site" button in normal mode.

**Comment by Scripter17** [comment]
Currenlty on Firefox 109.0 (25841) and it seems to still be an issue

Honestly I've given into apple's BS and switched to safari

I don't suppose it's the https://LocalIPAddress that's the issue? I might try wrangling ios into letting me add my own root certificate to see if we can rule that out

**Comment by jpann** [comment]
I wonder if this is happening because of this [About upcoming limits on trusted certificates](https://support.apple.com/en-us/102028), which prevents the self-signed certificate from being trusted on the iOS device. Once I recreate my certificate using a shorter validity period (< 398 days), I no longer have the issue.

**Comment by jbaconsult** [comment]
Is this still not fixed? Srsly? Why can’t FF mobile access the iOS certificate store and use that self-signed CA that is installed and trusted there?

**Comment by Scripter17** [comment]
Just re-installed FireFox and tested both with an installed CA and the same key with the CA removed; It seems to behave properly now

**Comment by tschenkelz** [comment]
From my perspective its not working properly.
I added the custom ca cert to ios trust store.
Firefox still says cert is signed by unknown authority.

I would really love to get this done with firefox.

**Comment by z400MB** [comment]
I completely agree with @jbaconsult . When will the problem be fixed?

**Comment by tismofied** [comment]
5 years and this is still an issue.

**Comment by eminetics** [comment]
6 years still a problem, fix it

**Comment by data-sync-user** [comment]
> **Raluca Iordan** commented from Jira:

This seems to be the same issue like [https://mozilla-hub.atlassian.net/browse/FXIOS-15250](https://mozilla-hub.atlassian.net/browse/FXIOS-15250|smart-link) - let’s wait to see if that is validated as fixed by QA and after that will also need to test it by QA to make sure we covered all the cases.

**Comment by janbrasna** [comment]
The original report is long resolved. For all of the followups I'd suggest trying now with the most recent version, whether what you think is an issue still reproduces, and then filing that specific case separately — for visibility and tracking purposes. Thanks.

**Comment by nexthop0** [comment]
> The original report is long resolved. For all of the followups I'd suggest trying now with the most recent version, whether what you think is an issue still reproduces, and then filing that specific case separately — for visibility and tracking purposes. Thanks.

Who made you the authority? It is 100% NOT fixed.

I have a self-signed CA in my lab. The cert is fully trusted in the iOS store. Works great on all my apps except Firefox. Still broken 6 years later.

**Comment by eminetics** [comment]
> > The original report is long resolved. For all of the followups I'd suggest trying now with the most recent version, whether what you think is an issue still reproduces, and then filing that specific case separately — for visibility and tracking purposes. Thanks.
> 
> Who made you the authority? It is 100% NOT fixed.
> 
> I have a self-signed CA in my lab. The cert is fully trusted in the iOS store. Works great on all my apps except Firefox. Still broken 6 years later.

This sounds like user error, please update your Firefox and clear cache. Etc… use private browser. This is a configuration issue as the issue has been resolved.

Thank you,
-D

**Comment by nexthop0** [comment]
> > > The original report is long resolved. For all of the followups I'd suggest trying now with the most recent version, whether what you think is an issue still reproduces, and then filing that specific case separately — for visibility and tracking purposes. Thanks.
> > 
> > 
> > Who made you the authority? It is 100% NOT fixed.
> > I have a self-signed CA in my lab. The cert is fully trusted in the iOS store. Works great on all my apps except Firefox. Still broken 6 years later.
> 
> This sounds like user error, please update your Firefox and clear cache. Etc… use private browser. This is a configuration issue as the issue has been resolved.
> 
> Thank you, -D

Your existence is user error. Works fine on all apps except Firefox. The cert is fully trusted in the iOS store (reiterated again since you can’t read). Safari, Chrome, and Brave show the site as secured and trusted. Firefox doesn’t. Your app sucks. Fix it.

**Comment by eminetics** [comment]
Please archive this case.

**Comment by huyz** [comment]
Still seems like an issue to me
