### ISSUE TITLE
Bug: Position data not showing for Pocket clicks

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8768]
[pocket_open_story_position](https://dictionary.telemetry.mozilla.org/apps/firefox_ios/metrics/pocket_open_story_position) was added in 34.1 to capture the position of the pocket tiles being clicked. However, the label is showing up as ```java
_other_
```

 or blank in looker. 

It seems we'll need to update our telemetry and send a label like Position-1 etc. You can see the errors in the current reporting here: https://mozilla.cloud.looker.com/explore/firefox_ios/metrics?qid=hgZm7V6OvNsIFZBPJ6uWLt&toggle=fil,vis

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2910)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Nishant Bhasin is this issue related to this one? https://github.com/mozilla-mobile/firefox-ios/issues/8709 ( https://github.com/mozilla-mobile/firefox-ios/issues/8709|smart-link )

**Comment by nbhasin2** [comment]
@SimonBasca #8709 is a different issue. This one is specific to label counter and should be fixed in looker app. If you still see `other` let me know and I'll investigate again.

**Comment by SimonBasca** [comment]
Fixed in https://github.com/mozilla-mobile/firefox-ios/pull/8878

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Nishant Bhasin I am still seeing other in the Glean dashboard. Should it not be fixed also in Glean? 

!image-20210803-080940.png|width=738,height=795!

This is tested on v36.0 (5718).

**Comment by data-sync-user** [comment]
➤ Jan-Erik Rediger commented:

It’s the uppercase P causing the issues. I sent a PR here: https://github.com/mozilla-mobile/firefox-ios/pull/8993 ( https://github.com/mozilla-mobile/firefox-ios/pull/8993|smart-link )
