### ISSUE TITLE
Localizations disappeared for a few locales after last l10n export

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#9632]
This happened in [this string export](https://github.com/mozilla-l10n/firefoxios-l10n/pull/122). 

We realized after merging that PR that the export was actually removing entire localizations from some locales. We noticed this is probably an issue with mapping in iOS tooling. For example, we have an `sv-SE` folder for Swedish, and on iOS I think that's just `sv`. 
I noticed later that we could have spotted that by looking at the list of locales in the dropdown in the "Jump to file" section of the PR: we can see there by scrolling down there are much more strings removed for certain locales than for others.

Affected locales:
* ga-IE - Irish
* nb-NO - Norwegian Bokmål
* nn-NO - Norwegian Nynorsk
* sat - Santali (Ol Chiki) 
* sv-SE - Swedish
* tl - Tagalog
* zgh - Tamazight

Link to our [PR fix](https://github.com/mozilla-l10n/firefoxios-l10n/pull/123#pullrequestreview-829550950).
CC @nishant2718 and CC @electricRGB for visibility.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3522)

**Comment by isabelrios** [comment]
In case this helps...I think the problem is related to how the locales are named in xcode and in shipping-locales.txt.. some examples:

Locale name in Bloczilla/*.lproj | Locale name shipping-locales.txt
-- | --
fil | tl
nn | nn-NO
nb | nb-NO
sv | sv-SE
en | en-US
ga | ga-IE

**Comment by nishant2718** [comment]
@isabelrios @Delphine yes that's it! The exporter's locale codes for those missing locales were changed. So previously, it would map `nn` to `nn-NO` but since `nn-NO` appears off the bat, that mapping failed. 

Thanks so much for looking into this - I'll make a quick PR today to correct that. [Here's the file](https://github.com/mozilla-mobile/LocalizationTools/blob/main/Sources/LocalizationTools/tasks/ExportTask.swift) for reference.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

I was able to test this issue on main 627116c2. 
The following locales work correctly: 

  * nb-NO - Norwegian Bokmål
  * nn-NO - Norwegian Nynorsk
  * sat - Santali (Ol Chiki) 
  * sv-SE - Swedish
  * sat - Santali (Ol Chiki)

However I did experience issues with other locales: 

  * I was unable to find tl - tagalog in iOS settings
  * ga-IE - Irish not fully localized 

!Screen Shot 2021-12-23 at 19.01.02.png|width=1420,height=929!

  * zgh - Tamazight is not localized. 

!video.mp4|width=828,height=1792!

Nishant Patel Please let me know if I should log separate issue for the locales with issues.

**Comment by Delphine** [comment]
I think this should have been fixed since then. Can you please retest those locales?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Delphine Lebedel the issues mentioned in the previous comment are still reproducible on main 63892e77b8016c2.

I’ve logged follow-up issues for the localization issues.

  * https://mozilla-hub.atlassian.net/browse/FXIOS-3581 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3581|smart-link ) 
  * https://mozilla-hub.atlassian.net/browse/FXIOS-3580 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3580|smart-link ) 

Note that I was unable to find tl - tagalog in iOS settings.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on 63892e77b80. Note we still have some issue with zgh - Tamazight but that will be fixed in https://mozilla-hub.atlassian.net/browse/FXIOS-3580 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3580|smart-link )

**Comment by nishant2718** [comment]
We've addressed this, so closing.
